[package]
name = "helm"
version = "0.1.0"
edition = "2024"

[dependencies]
jiff = { version = "0.2.21", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
uuid = { version = "1.21.0", features = ["v4", "serde"] }
